### ISSUE TITLE
Bad performance on ESP32S3-Pico

### ISSUE THREAD

**Issue by hiddej2** [bjoernQ/rust-esp32s3-ili9341#1]
First of all, thanks for making this, this is the only example of an ESP32 DMA implementation for the ILI9341 I could find in Rust.

But, when I try this example on the Waveshare ESP32-S3 Pico with a 2.4" ILI9341, everything works, but the performance is much worse (I count about 5 seconds per frame, not FPS) than your GIF.

I've changed nothing functional in the code, except this (different pins and changing the size):
```diff
--- a/src/main.rs
+++ b/src/main.rs
@@ -34,8 +34,8 @@ use mipidsi::Builder;
 
 mod spi_dma_displayinterface;
 
-const WIDTH: usize = 300;
-const HEIGHT: usize = 240;
+const WIDTH: usize = 200;
+const HEIGHT: usize = 200;
 const X_OFFSET: u16 = (320 - WIDTH as u16) / 2;
 const Y_OFFSET: u16 = (240 - HEIGHT as u16) / 2;
 
@@ -101,8 +101,8 @@ fn main() -> ! {
     let cs = io.pins.gpio5;
     let miso = io.pins.gpio2;
     let dc = io.pins.gpio4.into_push_pull_output();
-    let mut gpio_backlight = io.pins.gpio45.into_push_pull_output();
-    let rst = io.pins.gpio48.into_push_pull_output();
+    let mut gpio_backlight = io.pins.gpio39.into_push_pull_output();
+    let rst = io.pins.gpio40.into_push_pull_output();
 
     let dma = Gdma::new(peripherals.DMA);
     let dma_channel = dma.channel0;
@@ -142,7 +142,7 @@ fn main() -> ! {
 
     let mut display = Builder::ili9341_rgb565(di)
         .with_display_size(240, 320)
-        .with_orientation(mipidsi::Orientation::PortraitInverted(false))
+        .with_orientation(mipidsi::Orientation::Landscape(false))
         .with_color_order(mipidsi::ColorOrder::Bgr)
         .init(&mut delay, Some(rst))
         .unwrap();
```

Do you have any ideas on how I could improve the FPS?

**Comment by bjoernQ** [comment]
What might happen in your case is that the drawing code is doing a lot of very small SPI writes. My example code uses `set_pixels` with a large buffer so all those pixels are set with one SPI write.

If you draw graphics primitives or text it will most probably end-up having a single SPI write per pixel.

Setting up a DMA transfer is much more complex than using the FIFO so the performance using DMA gets worse than when using Non-DMA/FIFO mode

**Comment by hiddej2** [comment]
Hi, thanks for your comment.

I am using the exact same code as your example, with only the differences being different pins and render size. So, I'm not drawing graphics primitives or any text. Just drawing the framebuffer on screen.
I just connected a logic analyzer to visualize what's going on with the SPI bus, I discovered the following:

- Drawing 1 frame takes ~218ms
- There are 20 SPI write bursts per frame
- There is 9-10ms of inactivity on the SPI bus between these bursts
- There's ~4.9 seconds of inactivity on the SPI bus between two frames

The inactivity between these frames makes me believe that it takes almost 5 seconds in my case to calculate a single frame and put it in a framebuffer. I'm really puzzled on why this happens, as I'm using (almost) the exact same code and hardware as you, but I get much worse performance.

**Comment by bjoernQ** [comment]
> The inactivity between these frames makes me believe that it takes almost 5 seconds in my case to calculate a single frame and put it in a framebuffer

Yes, that is suspicious. Are you by any chance running the code compiled with the dev-profile? Code compiled in dev-mode is really, really slow

**Comment by hiddej2** [comment]
That was the problem, fixed it with running ```cargo run --release``` instad of ```cargo run``` 😅.
Thanks for helping me out.
