### ISSUE TITLE
The project freezes in wokwi at Builder::init

### ISSUE THREAD

**Issue by orsinium** [bjoernQ/rust-esp32s3-ili9341#2]
I tried running the project as-is in [wokwi](https://wokwi.com/) (an ESP32 emulator) but the code freezes at `mipidsi::builder::Builder::init` (line 103 in main.rs) and the screen stays black.

diagram.json:

```json
{
  "version": 1,
  "editor": "wokwi",
  "author": "orsinium",
  "parts": [
    {
      "type": "board-esp32-s3-devkitc-1",
      "id": "esp",
      "top": 136.38,
      "left": -1.28,
      "rotate": 270,
      "attrs": {}
    },
    {
      "type": "wokwi-ili9341",
      "id": "lcd1",
      "top": -55.61,
      "left": -38.21,
      "rotate": 270,
      "attrs": {}
    }
  ],
  "connections": [
    ["esp:TX", "$serialMonitor:RX", "", []],
    ["esp:RX", "$serialMonitor:TX", "", []],
    ["lcd1:SCK", "esp:7", "orange", ["h41.59", "v128.76", "h-180.28"]],
    ["lcd1:MOSI", "esp:6", "blue", ["h35.45", "v124.53", "h-164.54"]],
    ["lcd1:MISO", "esp:2", "blue", ["h35.45", "v124.53", "h-164.54"]],
    ["esp:GND.1", "lcd1:GND", "black", ["v12.64", "h65.1", "v-200.45"]],
    ["lcd1:CS", "esp:5", "black", ["h21.64", "v9.6"]],
    ["esp:4", "lcd1:D/C", "green", ["v24.15", "h244.8", "v-240.76"]],
    ["lcd1:VCC", "esp:5V", "red", ["h16.27", "v196.99", "h-65.22"]],
    ["esp:3V3.1", "lcd1:LED", "purple", ["h17.27", "v197.99", "h-67.22"]],
    ["esp:48", "lcd1:RST", "blue", ["h17.27", "v197.99", "h-67.22"]]
  ],
  "serialMonitor": {
    "display": "terminal"
  }
}
```

wokwi.toml:

```toml
[wokwi]
version = 1
gdbServerPort = 3333
elf = "target/xtensa-esp32s3-none-elf/debug/ili9431_esp32s3_test"
firmware = "target/xtensa-esp32s3-none-elf/debug/ili9431_esp32s3_test"
```

I'm building the debug version with `cargo build` and then running wokwi using the vscode extension.

The problem is most likely somewhere withing the DMA implementation (`spi_dma_displayinterface.rs`). When I replace `new_no_cs(...)` with `display_interface_spi::SPIInterface::new(...)`, it works.

![image](https://github.com/user-attachments/assets/fb47d0ff-0a6a-4832-a65a-8b41bcdafcf7)

**Comment by bjoernQ** [comment]
Thanks for letting me know about this.

In general, if something works on hardware but doesn't in the emulator that's something to be fixed in the emulator. I'm pretty sure our DMA implementation worked fine in Wokwi before - but we changed and optimized a few things which apparently makes it not work in Wokwi anymore.

I'm sure @urish is interested in this

**Comment by urish** [comment]
Hi, can you please open an issue on https://github.com/wokwi/wokwi-features so we can track it internally?

**Comment by orsinium** [comment]
Thank you all. Moved the issue to wokwi: https://github.com/wokwi/wokwi-features/issues/930
